### ISSUE TITLE
Please add support for Dyson Airpurifier Cool Tower (TP07 / 438E)

### ISSUE THREAD

**Issue by SilentServices** [Grizzelbee/ioBroker.dysonairpurifier#101]
Thank you for your effort with creating this adapter for the community. I have recently bought the TP07. Can you please add support for it?

TIA,
Michael

```
dysonairpurifier.0 | 2021-05-11 09:16:31.848 | warn | (8418) Please open an Issue on github if you think your device should be supported.
-- | -- | -- | --
dysonairpurifier.0 | 2021-05-11 09:16:31.847 | warn | (8418) Device with serial number [K1Y-EU-XXXXXXXX] not added, hence it is not supported by this adapter. Product type: [438E]
```

**Comment by Grizzelbee** [comment]
Thank for the nice words. :)
The 438E is already supported by the current development branch - but I'm still working on the 2-factor thing. So it will still take some time to the release. Please be patient. Support is comming. ;)

**Comment by Grizzelbee** [comment]
Supprt has been released with V0.9.0 on 15.05.2021.

**Comment by Grizzelbee** [comment]
Hi Michael,
I've just integrated the formaldehyd sensor in the 1.1.0 release and would now like to create an Index-field just like for the other sensor values. I assume that there is a scale for good (0 -> xx) , medium (xx+1 -> yy), bad (yy+1 -> zz), ... in the App as well.
May you please take a look into the App and report that scale to me? And - in addition - the value range of the sensor as it gets reported by the adapter?
I'm asking for these range because dyson often don't uses the direct values but devide them by 10 e.g. VOC-Index.

**Comment by SilentServices** [comment]
Good morning.
The HCHO Scale is as follows:
0.000-0.099 Good
0.100-0.299 Medium
0.300-0.499 Bad
0.500+ Very Bad

Can't tell about the value range as I only have the Purifier Cool without the HCOC Sensor.

Thank you for your work again. Muchg appreceated!

**Comment by Grizzelbee** [comment]
Thanx for that information. Very appretiated.
