### ISSUE TITLE
Error during dyson API login

### ISSUE THREAD

**Issue by a1development** [Grizzelbee/ioBroker.dysonairpurifier#12]
Hi, 

i just installed the latest version. 
After installation i have entered the Dyson Account Information, selected "Deutschland" from the drop down and left Celsius and 30 for the polling as is. 

The adapter turns yellow and in the Logs there are this error messages.
`
dysonairpurifier.0 | 2020-10-14 15:28:45.816 | error | at process._tickCallback (internal/process/next_tick.js:68:7)
-- | -- | -- | --
dysonairpurifier.0 | 2020-10-14 15:28:45.816 | error | at dysonAPILogIn.then.catch (C:\iobroker\SmartHome\node_modules\iobroker.dysonairpurifier\main.js:461:40)
dysonairpurifier.0 | 2020-10-14 15:28:45.816 | error | (12504) [main()] error: Cannot read property 'status' of undefined, stack: TypeError: Cannot read property 'status' of undefined
dysonairpurifier.0 | 2020-10-14 15:28:45.815 | error | at TLSSocket._finishInit (_tls_wrap.js:636:8)
dysonairpurifier.0 | 2020-10-14 15:28:45.815 | error | at TLSSocket.emit (events.js:198:13)
dysonairpurifier.0 | 2020-10-14 15:28:45.815 | error | at TLSSocket.onConnectSecure (_tls_wrap.js:1058:34)
dysonairpurifier.0 | 2020-10-14 15:28:45.815 | error | (12504) Error during dyson API login:Error: unable to verify the first certificate, Callstack: Error: unable to verify the first certificate
dysonairpurifier.0 | 2020-10-14 15:28:45.748 | info | (12504) starting. Version 0.4.0 in C:/iobroker/SmartHome/node_modules/iobroker.dysonairpurifier, node: v10.17.0, js-controller: 3.1.6
dysonairpurifier.0 | 2020-10-14 15:27:42.474 | info | (4748) Terminated (ADAPTER_REQUESTED_TERMINATION): Terminate Adapter until Configuration is completed
dysonairpurifier.0 | 2020-10-14 15:27:42.472 | error | (4748) Error during config validation: Given adapter config is invalid. Please fix.
dysonairpurifier.0 | 2020-10-14 15:27:42.463 | info | (4748) starting. Version 0.4.0 in C:/iobroker/SmartHome/node_modules/iobroker.dysonairpurifier, node: v10.17.0, js-controller: 3.1.6

`
After restarting the adapter, the same appeares in the log files.

I validated the credentials using the login on the dyson.com/de Webseite.

**Comment by Grizzelbee** [comment]
I faced this error yesterday the first time after invalidating my credrentials for a test. 
Unfortunately switching back to valid credentials didn't solved it again.
So I need to investigate on this error.

**Comment by a1development** [comment]
"Deuschland" is the correct country. 
I am happy to do some testing. Just let me know.

**Comment by Grizzelbee** [comment]
Fixed in 0.4.1 (2020-10-16).
Please close this issue, when it's working for you.

**Comment by a1development** [comment]
Works good! Thank you.

**Comment by a1development** [comment]
Well .. the only thing i missed is, that the adapter stays "yellow". 
But it works and all the values are updated etc.

**Comment by Grizzelbee** [comment]
Okay. This seems to me to be a new topic. For that I'd like to ask you to close this issue again (because it's solved) and open a new one regarding "Adapter stays in yellow state even it's online and working".
Best would be to 
* provide a complete **debug** log (even I'm currently not shure if there would be anything to see) from switching the adapter on - waiting 10 seconds and shut it down again - so I will get a complete cycle - but don't get frightend - debug-log is really very much. You may remove your mailaddess and encrypted password as well. I still need to remove these lines in code.
* please tell me something about your environment (How many dysons do you have? Which one(s)?) 
* It'll be fine for me to switch to german in this new case if you like.

**Comment by a1development** [comment]
OK.. Just checked the adapter again. Now it turns green directly. So all set. Thank you.
